inherit_gem:
  rubocop-rails-omakase: rubocop.yml

plugins:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Lint/EmptyFile:
  Enabled: true

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: no_space

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 10

RSpec/MultipleDescribes:
  Enabled: false

Security/Eval:
  Exclude:
    - spec/light/services/error_spec.rb

Style/ClassAndModuleChildren:
  Exclude:
    - spec/data/services/**/*.rb

Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets