require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/GuardClause:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - spec/data/services/**/*.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
