require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/GuardClause:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - spec/data/services/**/*.rb
