plugins:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-performance

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  TargetRubyVersion: 3

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: no_space

Lint/EmptyFile:
  Enabled: true

Metrics/AbcSize:
  Exclude:
    - lib/light/services/dsl/steps_dsl.rb
    - lib/light/services/messages.rb
  Max: 20

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Metrics/ClassLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 10

Naming/PredicatePrefix:
  Enabled: false

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleDescribes:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 10

RSpec/NestedGroups:
  Max: 5

Security/Eval:
  Exclude:
    - spec/light/services/error_spec.rb

Style/ClassAndModuleChildren:
  Exclude:
    - spec/data/services/**/*.rb

Style/ClassVars:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/OptionalBooleanParameter:
  Exclude:
    - lib/light/services/rspec/matchers/**/*.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: diff_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/WordArray:
  EnforcedStyle: brackets

Style/NumericPredicate:
  Enabled: false