sudo: false
language: ruby

rvm:
  - 2.3.3

before_install: gem install bundler -v 1.12.5

gemfile:
  - gemfiles/rails_4_0.gemfile
  - gemfiles/rails_4_1.gemfile
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5_0.gemfile

addons:
  code_climate:
    repo_token: dedf6049120e32b166263dd9e07b2abea3991a18b2d0c8dc86792776ca7578ce
