# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module ::MarshalableContainer; end
module ::Rails::Generators::Base; end
module ::TestServiceWithMissingType; end
module ::TestStepService; end
module RubyIndexer::DeclarationListener; end
module RubyLsp::Addon; end
